//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4214
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServ_cltponto")]
public interface IServ_cltponto
{
    
    // CODEGEN: O parâmetro 'GetCltPontoResult' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ_cltponto/GetCltPonto", ReplyAction="http://tempuri.org/IServ_cltponto/GetCltPontoResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetCltPontoResponse GetCltPonto(GetCltPontoRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCltPonto", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetCltPontoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string path;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public System.DateTime inicio;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public System.DateTime fim;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string tipo;
    
    public GetCltPontoRequest()
    {
    }
    
    public GetCltPontoRequest(string path, System.DateTime inicio, System.DateTime fim, string tipo)
    {
        this.path = path;
        this.inicio = inicio;
        this.fim = fim;
        this.tipo = tipo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCltPontoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetCltPontoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet GetCltPontoResult;
    
    public GetCltPontoResponse()
    {
    }
    
    public GetCltPontoResponse(System.Data.DataSet GetCltPontoResult)
    {
        this.GetCltPontoResult = GetCltPontoResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServ_cltpontoChannel : IServ_cltponto, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Serv_cltpontoClient : System.ServiceModel.ClientBase<IServ_cltponto>, IServ_cltponto
{
    
    public Serv_cltpontoClient()
    {
    }
    
    public Serv_cltpontoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Serv_cltpontoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Serv_cltpontoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Serv_cltpontoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCltPontoResponse IServ_cltponto.GetCltPonto(GetCltPontoRequest request)
    {
        return base.Channel.GetCltPonto(request);
    }
    
    public System.Data.DataSet GetCltPonto(string path, System.DateTime inicio, System.DateTime fim, string tipo)
    {
        GetCltPontoRequest inValue = new GetCltPontoRequest();
        inValue.path = path;
        inValue.inicio = inicio;
        inValue.fim = fim;
        inValue.tipo = tipo;
        GetCltPontoResponse retVal = ((IServ_cltponto)(this)).GetCltPonto(inValue);
        return retVal.GetCltPontoResult;
    }
}
